In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("StudentsPerformance.csv");

In [7]:
df

,Math_score,Reading_score,Writing_score,Placement_score,Club_Join_Date,Placement_Offer_Count
0,80.0,90.0,70.0,77,2018,2
1,70.0,77.0,76.0,85,2018,3
2,62.0,88.0,68.0,92,2019,3
3,94.0,84.0,71.0,78,2019,2
4,78.0,81.0,62.0,100,2020,3
5,77.0,200.0,73.0,82,2020,2
6,77.0,75.0,65.0,100,2020,3
7,62.0,80.0,63.0,97,2019,3
8,79.0,88.0,65.0,82,2018,2
9,63.0,94.0,73.0,79,2021,1
10,66.0,79.0,77.0,80,2019,2
11,69.0,78.0,77.0,90,2020,3
12,80.0,88.0,77.0,77,2018,2
13,66.0,90.0,72.0,93,2020,3
14,64.0,90.0,67.0,79,2020,2
15,78.0,86.0,64.0,76,2019,2
16,61.0,95.0,64.0,75,2021,2
17,180.0,82.0,76.0,95,2019,3
18,80.0,90.0,74.0,81,2019,2
19,70.0,82.0,NaN,89,2020,3
20,69.0,83.0,74.0,77,2021,2
21,71.0,81.0,63.0,91,2020,3
22,71.0,91.0,61.0,75,2020,2
23,61.0,78.0,69.0,75,2020,2
24,NaN,81.0,66.0,81,2019,2
25,76.0,83.0,79.0,77,2019,2
26,68.0,87.0,76.0,95,2020,3
27,61.0,75.0,63.0,93,2020,3
28,80.0,NaN,61.0,100,2020,3
29,65.0,78.0,73.0,98,2018,3

In [4]:
df.head()

,Math_score,Reading_score,Writing_score,Placement_score,Club_Join_Date,Placement_Offer_Count
0,80.0,90.0,70.0,77,2018,2
1,70.0,77.0,76.0,85,2018,3
2,62.0,88.0,68.0,92,2019,3
3,94.0,84.0,71.0,78,2019,2
4,78.0,81.0,62.0,100,2020,3

In [5]:
df.tail()

,Math_score,Reading_score,Writing_score,Placement_score,Club_Join_Date,Placement_Offer_Count
25,76.0,83.0,79.0,77,2019,2
26,68.0,87.0,76.0,95,2020,3
27,61.0,75.0,63.0,93,2020,3
28,80.0,NaN,61.0,100,2020,3
29,65.0,78.0,73.0,98,2018,3

In [8]:
df.index

RangeIndex(start=0, stop=30, step=1)

In [9]:
df.columns

Index(['Math_score', 'Reading_score', 'Writing_score', 'Placement_score',
       'Club_Join_Date', 'Placement_Offer_Count'],
      dtype='object')

In [10]:
df.shape

(30, 6)

In [11]:
df.dtypes

Math_score               float64
Reading_score            float64
Writing_score            float64
Placement_score            int64
Club_Join_Date             int64
Placement_Offer_Count      int64
dtype: object

In [12]:
df.columns.values

array(['Math_score', 'Reading_score', 'Writing_score', 'Placement_score',
       'Club_Join_Date', 'Placement_Offer_Count'], dtype=object)

In [13]:
df.columns.values.tolist()

['Math_score',
 'Reading_score',
 'Writing_score',
 'Placement_score',
 'Club_Join_Date',
 'Placement_Offer_Count']

In [15]:
df['Math_score']

0      80.0
1      70.0
2      62.0
3      94.0
4      78.0
5      77.0
6      77.0
7      62.0
8      79.0
9      63.0
10     66.0
11     69.0
12     80.0
13     66.0
14     64.0
15     78.0
16     61.0
17    180.0
18     80.0
19     70.0
20     69.0
21     71.0
22     71.0
23     61.0
24      NaN
25     76.0
26     68.0
27     61.0
28     80.0
29     65.0
Name: Math_score, dtype: float64

In [16]:
df.to_numpy

<bound method DataFrame.to_numpy of     Math_score  Reading_score  Writing_score  Placement_score  Club_Join_Date  \
0         80.0           90.0           70.0               77            2018
1         70.0           77.0           76.0               85            2018
2         62.0           88.0           68.0               92            2019
3         94.0           84.0           71.0               78            2019
4         78.0           81.0           62.0              100            2020
5         77.0          200.0           73.0               82            2020
6         77.0           75.0           65.0              100            2020
7         62.0           80.0           63.0               97            2019
8         79.0           88.0           65.0               82            2018
9         63.0           94.0           73.0               79            2021
10        66.0           79.0           77.0               80            2019
11        69.0           78.0           77.0               90            2020
12        80.0           88.0           77.0               77            2018
13        66.0           90.0           72.0               93            2020
14        64.0           90.0           67.0               79            2020
15        78.0           86.0           64.0               76            2019
16        61.0           95.0           64.0               75            2021
17       180.0           82.0           76.0               95            2019
18        80.0           90.0           74.0               81            2019
19        70.0           82.0            NaN               89            2020
20        69.0           83.0           74.0               77            2021
21        71.0           81.0           63.0               91            2020
22        71.0           91.0           61.0               75            2020
23        61.0           78.0           69.0               75            2020
24         NaN           81.0           66.0               81            2019
25        76.0           83.0           79.0               77            2019
26        68.0           87.0           76.0               95            2020
27        61.0           75.0           63.0               93            2020
28        80.0            NaN           61.0              100            2020
29        65.0           78.0           73.0               98            2018

    Placement_Offer_Count
0                       2
1                       3
2                       3
3                       2
4                       3
5                       2
6                       3
7                       3
8                       2
9                       1
10                      2
11                      3
12                      2
13                      3
14                      2
15                      2
16                      2
17                      3
18                      2
19                      3
20                      2
21                      3
22                      2
23                      2
24                      2
25                      2
26                      3
27                      3
28                      3
29                      3  >

In [17]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
Math_score,80.0,70.0,62.0,94.0,78.0,77.0,77.0,62.0,79.0,63.0,...,69.0,71.0,71.0,61.0,NaN,76.0,68.0,61.0,80.0,65.0
Reading_score,90.0,77.0,88.0,84.0,81.0,200.0,75.0,80.0,88.0,94.0,...,83.0,81.0,91.0,78.0,81.0,83.0,87.0,75.0,NaN,78.0
Writing_score,70.0,76.0,68.0,71.0,62.0,73.0,65.0,63.0,65.0,73.0,...,74.0,63.0,61.0,69.0,66.0,79.0,76.0,63.0,61.0,73.0
Placement_score,77.0,85.0,92.0,78.0,100.0,82.0,100.0,97.0,82.0,79.0,...,77.0,91.0,75.0,75.0,81.0,77.0,95.0,93.0,100.0,98.0
Club_Join_Date,2018.0,2018.0,2019.0,2019.0,2020.0,2020.0,2020.0,2019.0,2018.0,2021.0,...,2021.0,2020.0,2020.0,2020.0,2019.0,2019.0,2020.0,2020.0,2020.0,2018.0
Placement_Offer_Count,2.0,3.0,3.0,2.0,3.0,2.0,3.0,3.0,2.0,1.0,...,2.0,3.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0

In [18]:
df.sort_index(axis = 1 , ascending = True)

,Club_Join_Date,Math_score,Placement_Offer_Count,Placement_score,Reading_score,Writing_score
0,2018,80.0,2,77,90.0,70.0
1,2018,70.0,3,85,77.0,76.0
2,2019,62.0,3,92,88.0,68.0
3,2019,94.0,2,78,84.0,71.0
4,2020,78.0,3,100,81.0,62.0
5,2020,77.0,2,82,200.0,73.0
6,2020,77.0,3,100,75.0,65.0
7,2019,62.0,3,97,80.0,63.0
8,2018,79.0,2,82,88.0,65.0
9,2021,63.0,1,79,94.0,73.0
10,2019,66.0,2,80,79.0,77.0
11,2020,69.0,3,90,78.0,77.0
12,2018,80.0,2,77,88.0,77.0
13,2020,66.0,3,93,90.0,72.0
14,2020,64.0,2,79,90.0,67.0
15,2019,78.0,2,76,86.0,64.0
16,2021,61.0,2,75,95.0,64.0
17,2019,180.0,3,95,82.0,76.0
18,2019,80.0,2,81,90.0,74.0
19,2020,70.0,3,89,82.0,NaN
20,2021,69.0,2,77,83.0,74.0
21,2020,71.0,3,91,81.0,63.0
22,2020,71.0,2,75,91.0,61.0
23,2020,61.0,2,75,78.0,69.0
24,2019,NaN,2,81,81.0,66.0
25,2019,76.0,2,77,83.0,79.0
26,2020,68.0,3,95,87.0,76.0
27,2020,61.0,3,93,75.0,63.0
28,2020,80.0,3,100,NaN,61.0
29,2018,65.0,3,98,78.0,73.0

In [22]:
df.sort_index(axis = 0 , ascending = False)

,Math_score,Reading_score,Writing_score,Placement_score,Club_Join_Date,Placement_Offer_Count
29,65.0,78.0,73.0,98,2018,3
28,80.0,NaN,61.0,100,2020,3
27,61.0,75.0,63.0,93,2020,3
26,68.0,87.0,76.0,95,2020,3
25,76.0,83.0,79.0,77,2019,2
24,NaN,81.0,66.0,81,2019,2
23,61.0,78.0,69.0,75,2020,2
22,71.0,91.0,61.0,75,2020,2
21,71.0,81.0,63.0,91,2020,3
20,69.0,83.0,74.0,77,2021,2
19,70.0,82.0,NaN,89,2020,3
18,80.0,90.0,74.0,81,2019,2
17,180.0,82.0,76.0,95,2019,3
16,61.0,95.0,64.0,75,2021,2
15,78.0,86.0,64.0,76,2019,2
14,64.0,90.0,67.0,79,2020,2
13,66.0,90.0,72.0,93,2020,3
12,80.0,88.0,77.0,77,2018,2
11,69.0,78.0,77.0,90,2020,3
10,66.0,79.0,77.0,80,2019,2
9,63.0,94.0,73.0,79,2021,1
8,79.0,88.0,65.0,82,2018,2
7,62.0,80.0,63.0,97,2019,3
6,77.0,75.0,65.0,100,2020,3
5,77.0,200.0,73.0,82,2020,2
4,78.0,81.0,62.0,100,2020,3
3,94.0,84.0,71.0,78,2019,2
2,62.0,88.0,68.0,92,2019,3
1,70.0,77.0,76.0,85,2018,3
0,80.0,90.0,70.0,77,2018,2

In [23]:
df.sort_values(by="Club_Join_Date")

,Math_score,Reading_score,Writing_score,Placement_score,Club_Join_Date,Placement_Offer_Count
0,80.0,90.0,70.0,77,2018,2
12,80.0,88.0,77.0,77,2018,2
8,79.0,88.0,65.0,82,2018,2
29,65.0,78.0,73.0,98,2018,3
1,70.0,77.0,76.0,85,2018,3
7,62.0,80.0,63.0,97,2019,3
2,62.0,88.0,68.0,92,2019,3
25,76.0,83.0,79.0,77,2019,2
10,66.0,79.0,77.0,80,2019,2
24,NaN,81.0,66.0,81,2019,2
15,78.0,86.0,64.0,76,2019,2
3,94.0,84.0,71.0,78,2019,2
17,180.0,82.0,76.0,95,2019,3
18,80.0,90.0,74.0,81,2019,2
4,78.0,81.0,62.0,100,2020,3
27,61.0,75.0,63.0,93,2020,3
26,68.0,87.0,76.0,95,2020,3
23,61.0,78.0,69.0,75,2020,2
22,71.0,91.0,61.0,75,2020,2
21,71.0,81.0,63.0,91,2020,3
14,64.0,90.0,67.0,79,2020,2
19,70.0,82.0,NaN,89,2020,3
28,80.0,NaN,61.0,100,2020,3
13,66.0,90.0,72.0,93,2020,3
11,69.0,78.0,77.0,90,2020,3
6,77.0,75.0,65.0,100,2020,3
5,77.0,200.0,73.0,82,2020,2
9,63.0,94.0,73.0,79,2021,1
20,69.0,83.0,74.0,77,2021,2
16,61.0,95.0,64.0,75,2021,2

In [24]:
df.isnull()

,Math_score,Reading_score,Writing_score,Placement_score,Club_Join_Date,Placement_Offer_Count
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,True,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,True,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,True,False,False,False,False
29,False,False,False,False,False,False

In [25]:
df.notnull()

,Math_score,Reading_score,Writing_score,Placement_score,Club_Join_Date,Placement_Offer_Count
0,True,True,True,True,True,True
1,True,True,True,True,True,True
2,True,True,True,True,True,True
3,True,True,True,True,True,True
4,True,True,True,True,True,True
5,True,True,True,True,True,True
6,True,True,True,True,True,True
7,True,True,True,True,True,True
8,True,True,True,True,True,True
9,True,True,True,True,True,True
10,True,True,True,True,True,True
11,True,True,True,True,True,True
12,True,True,True,True,True,True
13,True,True,True,True,True,True
14,True,True,True,True,True,True
15,True,True,True,True,True,True
16,True,True,True,True,True,True
17,True,True,True,True,True,True
18,True,True,True,True,True,True
19,True,True,False,True,True,True
20,True,True,True,True,True,True
21,True,True,True,True,True,True
22,True,True,True,True,True,True
23,True,True,True,True,True,True
24,False,True,True,True,True,True
25,True,True,True,True,True,True
26,True,True,True,True,True,True
27,True,True,True,True,True,True
28,True,False,True,True,True,True
29,True,True,True,True,True,True

In [26]:
df.isnull().values.any()

True

In [27]:
df.notnull().sum()

Math_score               29
Reading_score            29
Writing_score            29
Placement_score          30
Club_Join_Date           30
Placement_Offer_Count    30
dtype: int64

In [28]:
df.iloc[5]

Math_score                 77.0
Reading_score             200.0
Writing_score              73.0
Placement_score            82.0
Club_Join_Date           2020.0
Placement_Offer_Count       2.0
Name: 5, dtype: float64

In [29]:
df.iloc[2]

Math_score                 62.0
Reading_score              88.0
Writing_score              68.0
Placement_score            92.0
Club_Join_Date           2019.0
Placement_Offer_Count       3.0
Name: 2, dtype: float64

In [30]:
df.describe()

,Math_score,Reading_score,Writing_score,Placement_score,Club_Join_Date,Placement_Offer_Count
count,29.000000,29.000000,29.000000,30.000000,30.000000,30.000000
mean,75.103448,88.068966,69.620690,85.633333,2019.466667,2.433333
std,21.699810,22.238851,5.734693,8.833648,0.899553,0.568321
min,61.000000,75.000000,61.000000,75.000000,2018.000000,1.000000
25%,65.000000,80.000000,64.000000,77.250000,2019.000000,2.000000
50%,70.000000,83.000000,70.000000,82.000000,2020.000000,2.000000
75%,78.000000,90.000000,74.000000,93.000000,2020.000000,3.000000
max,180.000000,200.000000,79.000000,100.000000,2021.000000,3.000000

In [31]:
df.fillna(0)

,Math_score,Reading_score,Writing_score,Placement_score,Club_Join_Date,Placement_Offer_Count
0,80.0,90.0,70.0,77,2018,2
1,70.0,77.0,76.0,85,2018,3
2,62.0,88.0,68.0,92,2019,3
3,94.0,84.0,71.0,78,2019,2
4,78.0,81.0,62.0,100,2020,3
5,77.0,200.0,73.0,82,2020,2
6,77.0,75.0,65.0,100,2020,3
7,62.0,80.0,63.0,97,2019,3
8,79.0,88.0,65.0,82,2018,2
9,63.0,94.0,73.0,79,2021,1
10,66.0,79.0,77.0,80,2019,2
11,69.0,78.0,77.0,90,2020,3
12,80.0,88.0,77.0,77,2018,2
13,66.0,90.0,72.0,93,2020,3
14,64.0,90.0,67.0,79,2020,2
15,78.0,86.0,64.0,76,2019,2
16,61.0,95.0,64.0,75,2021,2
17,180.0,82.0,76.0,95,2019,3
18,80.0,90.0,74.0,81,2019,2
19,70.0,82.0,0.0,89,2020,3
20,69.0,83.0,74.0,77,2021,2
21,71.0,81.0,63.0,91,2020,3
22,71.0,91.0,61.0,75,2020,2
23,61.0,78.0,69.0,75,2020,2
24,0.0,81.0,66.0,81,2019,2
25,76.0,83.0,79.0,77,2019,2
26,68.0,87.0,76.0,95,2020,3
27,61.0,75.0,63.0,93,2020,3
28,80.0,0.0,61.0,100,2020,3
29,65.0,78.0,73.0,98,2018,3

In [32]:
df.mean()

Math_score                 75.103448
Reading_score              88.068966
Writing_score              69.620690
Placement_score            85.633333
Club_Join_Date           2019.466667
Placement_Offer_Count       2.433333
dtype: float64

In [33]:
df.median()

Math_score                 70.0
Reading_score              83.0
Writing_score              70.0
Placement_score            82.0
Club_Join_Date           2020.0
Placement_Offer_Count       2.0
dtype: float64

In [34]:
df.mode()

,Math_score,Reading_score,Writing_score,Placement_score,Club_Join_Date,Placement_Offer_Count
0,80.0,90.0,63.0,77.0,2020.0,2.0
1,NaN,NaN,73.0,NaN,NaN,NaN
2,NaN,NaN,76.0,NaN,NaN,NaN
3,NaN,NaN,77.0,NaN,NaN,NaN

In [35]:
df.head()

,Math_score,Reading_score,Writing_score,Placement_score,Club_Join_Date,Placement_Offer_Count
0,80.0,90.0,70.0,77,2018,2
1,70.0,77.0,76.0,85,2018,3
2,62.0,88.0,68.0,92,2019,3
3,94.0,84.0,71.0,78,2019,2
4,78.0,81.0,62.0,100,2020,3

In [36]:
df

,Math_score,Reading_score,Writing_score,Placement_score,Club_Join_Date,Placement_Offer_Count
0,80.0,90.0,70.0,77,2018,2
1,70.0,77.0,76.0,85,2018,3
2,62.0,88.0,68.0,92,2019,3
3,94.0,84.0,71.0,78,2019,2
4,78.0,81.0,62.0,100,2020,3
5,77.0,200.0,73.0,82,2020,2
6,77.0,75.0,65.0,100,2020,3
7,62.0,80.0,63.0,97,2019,3
8,79.0,88.0,65.0,82,2018,2
9,63.0,94.0,73.0,79,2021,1
10,66.0,79.0,77.0,80,2019,2
11,69.0,78.0,77.0,90,2020,3
12,80.0,88.0,77.0,77,2018,2
13,66.0,90.0,72.0,93,2020,3
14,64.0,90.0,67.0,79,2020,2
15,78.0,86.0,64.0,76,2019,2
16,61.0,95.0,64.0,75,2021,2
17,180.0,82.0,76.0,95,2019,3
18,80.0,90.0,74.0,81,2019,2
19,70.0,82.0,NaN,89,2020,3
20,69.0,83.0,74.0,77,2021,2
21,71.0,81.0,63.0,91,2020,3
22,71.0,91.0,61.0,75,2020,2
23,61.0,78.0,69.0,75,2020,2
24,NaN,81.0,66.0,81,2019,2
25,76.0,83.0,79.0,77,2019,2
26,68.0,87.0,76.0,95,2020,3
27,61.0,75.0,63.0,93,2020,3
28,80.0,NaN,61.0,100,2020,3
29,65.0,78.0,73.0,98,2018,3