In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("Mall_Customers.csv")

In [5]:
df

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [8]:
df.head()

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [9]:
df.shape

(200, 5)

In [10]:
df.dtypes

CustomerID                 int64
Genre                     object
Age                        int64
Annual Income (k$)         int64
Spending Score (1-100)     int64
dtype: object

In [11]:
df.info

<bound method DataFrame.info of      CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]>

In [12]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [13]:
df.mean(numeric_only = True)

CustomerID                100.50
Age                        38.85
Annual Income (k$)         60.56
Spending Score (1-100)     50.20
dtype: float64

In [14]:
df.median(numeric_only = True)

CustomerID                100.5
Age                        36.0
Annual Income (k$)         61.5
Spending Score (1-100)     50.0
dtype: float64

In [15]:
df.mode(numeric_only = True)

     CustomerID   Age  Annual Income (k$)  Spending Score (1-100)
0             1  32.0                54.0                    42.0
1             2   NaN                78.0                     NaN
2             3   NaN                 NaN                     NaN
3             4   NaN                 NaN                     NaN
4             5   NaN                 NaN                     NaN
..          ...   ...                 ...                     ...
195         196   NaN                 NaN                     NaN
196         197   NaN                 NaN                     NaN
197         198   NaN                 NaN                     NaN
198         199   NaN                 NaN                     NaN
199         200   NaN                 NaN                     NaN

[200 rows x 4 columns]

In [16]:
df["Age"].min()

18

In [17]:
df["Age"].max()

70

In [18]:
df["Age"].mean()

38.85

In [19]:
df["Age"].median()

36.0

In [20]:
df["Age"].mode()

0    32
Name: Age, dtype: int64

In [21]:
df["Age"].std()

13.969007331558883

In [22]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [23]:
df["Annual Income (k$)"].min()

15

In [24]:
df["Annual Income (k$)"].max()

137

In [25]:
df["Annual Income (k$)"].mean()

60.56

In [26]:
df["Annual Income (k$)"].median()

61.5

In [27]:
df["Annual Income (k$)"].mode()

0    54
1    78
Name: Annual Income (k$), dtype: int64

In [28]:
df["Annual Income (k$)"].std()

26.264721165271254

In [30]:
grp1.first()

     CustomerID   Genre  Annual Income (k$)  Spending Score (1-100)
Age
18           34    Male                  33                      92
19            1    Male                  15                      39
20            3  Female                  16                       6
21            2    Male                  15                      81
22            6  Female                  17                      76
23            4  Female                  16                      77
24           14  Female                  20                      77
25           22    Male                  24                      73
26           76    Male                  54                      54
27           48  Female                  40                      47
28          143  Female                  76                      40
29           26    Male                  28                      82
30           10  Female                  19                      72
31            5  Female                  17                      40
32           70  Female                  48                      47
33           52    Male                  42                      60
34           89  Female                  58                      60
35            7  Female                  18                       6
36           39  Female                  37                      26
37           15    Male                  20                      13
38           82    Male                  54                      55
39          124    Male                  69                      91
40           29  Female                  29                      31
41          185  Female                  99                      39
42           37  Female                  34                      17
43           67  Female                  48                      50
44          137  Female                  73                       7
45           27  Female                  28                      32
46           23  Female                  25                       5
47           56    Male                  43                      41
48           43    Male                  39                      36
49           35  Female                  33                      14
50           47  Female                  40                      55
51           57  Female                  44                      50
52           19    Male                  23                      29
53           33    Male                  33                       4
54           25  Female                  28                      14
55           87  Female                  57                      58
56          161  Female                  79                      35
57           81    Male                  54                      51
58           13  Female                  20                      15
59           54    Male                  43                      60
60           31    Male                  30                       4
63           65    Male                  48                      51
64            9    Male                  19                       3
65           41  Female                  38                      35
66          107  Female                  63                      50
67           11    Male                  19                      14
68           68  Female                  48                      48
69           58    Male                  44                      46
70           61    Male                  46                      56

In [29]:
grp1 = df.groupby("Age")

In [31]:
grp2 = df.groupby("Genre")

In [32]:
grp2

In [33]:
grp2.first()

        CustomerID  Age  Annual Income (k$)  Spending Score (1-100)
Genre
Female           3   20                  16                       6
Male             1   19                  15                      39

In [35]:
grp2.get_group("Male")

     CustomerID Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1  Male   19                  15                      39
1             2  Male   21                  15                      81
8             9  Male   64                  19                       3
10           11  Male   67                  19                      14
14           15  Male   37                  20                      13
..          ...   ...  ...                 ...                     ...
187         188  Male   28                 101                      68
192         193  Male   33                 113                       8
197         198  Male   32                 126                      74
198         199  Male   32                 137                      18
199         200  Male   30                 137                      83

[88 rows x 5 columns]

In [36]:
grp2.get_group("Female")

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
..          ...     ...  ...                 ...                     ...
191         192  Female   32                 103                      69
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28

[112 rows x 5 columns]

In [37]:
df.groupby("Genre").mean()

        CustomerID        Age  Annual Income (k$)  Spending Score (1-100)
Genre
Female   97.562500  38.098214           59.250000               51.526786
Male    104.238636  39.806818           62.227273               48.511364

In [43]:
df2 = pd.read_csv("Iris.csv")

In [44]:
df2

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [45]:
df2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [47]:
df2.shape

(150, 6)

In [48]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [49]:
df2.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [50]:
df2.groupby("Species")

In [51]:
df2.groupby("Species").mean()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Species,,,,,
Iris-setosa,25.5,5.006,3.418,1.464,0.244
Iris-versicolor,75.5,5.936,2.770,4.260,1.326
Iris-virginica,125.5,6.588,2.974,5.552,2.026