In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

df=pd.read_csv("Mall_Customers.csv")

In [21]:
df=pd.read_csv("Mall_Customers.csv")

In [22]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [23]:
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [24]:
group = df.groupby('Age')['Annual Income (k$)'].agg(['mean', 'median', 'min', 'max', 'std'])
group

           mean  median  min  max        std
Age
18    51.250000    53.5   33   65  14.056434
19    57.000000    63.5   15   81  20.632845
20    41.600000    37.0   16   73  24.815318
21    38.800000    33.0   15   62  19.018412
22    31.333333    20.0   17   57  22.278540
23    41.500000    41.5   16   70  23.441416
24    39.250000    38.5   20   60  16.357975
25    57.666667    72.0   24   77  29.263174
26    58.000000    58.0   54   62   5.656854
27    63.166667    63.5   40   88  18.400181
28    85.250000    82.0   76  101  11.615363
29    63.600000    73.0   28   98  28.866936
30    76.142857    78.0   19  137  39.612408
31    48.375000    41.5   17   81  23.323425
32    87.181818    77.0   48  137  26.809768
33    80.333333    86.0   42  113  35.837597
34    79.000000    78.0   58  103  15.968719
35    46.666667    24.0   18  120  38.632888
36    81.000000    87.0   37  103  22.556595
37    65.000000    78.0   20   97  40.112342
38    74.500000    69.0   54  113  20.462160
39    72.666667    71.0   69   78   4.725816
40    61.666667    64.5   29   87  19.551641
41   101.000000   101.0   99  103   2.828427
42    60.000000    60.0   34   86  36.769553
43    65.666667    71.0   48   78  15.695010
44    75.500000    75.5   73   78   3.535534
45    69.333333    54.0   28  126  50.767444
46    59.000000    54.0   25   98  36.755952
47    70.166667    65.5   43  120  27.694163
48    58.200000    60.0   39   77  13.700365
49    51.000000    54.0   33   65  12.884099
50    58.600000    58.0   40   85  18.420098
51    55.500000    55.5   44   67  16.263456
52    55.500000    55.5   23   88  45.961941
53    39.500000    39.5   33   46   9.192388
54    59.750000    55.0   28  101  30.998656
55    57.000000    57.0   57   57        NaN
56    79.000000    79.0   79   79        NaN
57    64.500000    64.5   54   75  14.849242
58    54.000000    54.0   20   88  48.083261
59    65.250000    62.5   43   93  21.792583
60    43.333333    50.0   30   50  11.547005
63    56.500000    56.5   48   65  12.020815
64    19.000000    19.0   19   19        NaN
65    50.500000    50.5   38   63  17.677670
66    63.000000    63.0   63   63   0.000000
67    45.500000    50.5   19   62  18.699376
68    56.666667    59.0   48   63   7.767453
69    44.000000    44.0   44   44        NaN
70    47.500000    47.5   46   49   2.121320

In [26]:
print('Summary statistics for Age grouped by Genre:')
df.groupby('Gender')['Age'].agg(['mean', 'median', 'min', 'max', 'std'])

Summary statistics for Age grouped by Genre:

             mean  median  min  max        std
Gender
Female  38.098214    35.0   18   68  12.644095
Male    39.806818    37.0   18   70  15.514812

In [27]:
print('summary statistics for age grouped by spending score:')
df.groupby('Age')['Spending Score (1-100)'].agg(['mean','median','min','max','std'])

summary statistics for age grouped by spending score:

          mean  median  min  max        std
Age
18   60.000000    53.5   41   92  22.583180
19   39.750000    48.0    5   59  20.851516
20   40.200000    49.0    5   75  33.025748
21   66.800000    73.0   42   81  16.976454
22   70.000000    76.0   55   79  13.076697
23   63.333333    64.5   29   94  26.432303
24   71.500000    71.0   52   92  17.058722
25   39.666667    34.0   12   73  30.892286
26   54.500000    54.5   54   55   0.707107
27   60.333333    53.5   47   89  16.045768
28   70.000000    71.5   40   97  23.508864
29   76.600000    83.0   42   88  19.539703
30   80.285714    78.0   72   97   9.123491
31   63.875000    66.0   40   93  18.161478
32   66.000000    73.0   18   93  22.374092
33   54.333333    60.0    8   95  43.775945
34   39.200000    23.0    1   90  35.464066
35   63.888889    72.0    6   99  32.405418
36   52.500000    51.0   10   92  35.444323
37   15.333333    13.0    1   32  15.631165
38   63.166667    65.0   40   91  20.643805
39   84.666667    88.0   75   91   8.504901
40   47.500000    44.0   13   95  27.876513
41   28.000000    28.0   17   39  15.556349
42   18.500000    18.5   17   20   2.121320
43   34.000000    35.0   17   50  16.522712
44   13.500000    13.5    7   20   9.192388
45   37.666667    32.0   28   53  13.428825
46   21.333333    15.0    5   44  20.256686
47   28.500000    28.5    9   47  16.574076
48   41.800000    42.0   36   49   5.848077
49   42.714286    48.0   14   59  16.316804
50   45.800000    46.0   26   57  12.275993
51   46.500000    46.5   43   50   4.949747
52   21.000000    21.0   13   29  11.313708
53   25.000000    25.0    4   46  29.698485
54   35.750000    35.0   14   59  20.467454
55   58.000000    58.0   58   58        NaN
56   35.000000    35.0   35   35        NaN
57   28.000000    28.0    5   51  32.526912
58   15.000000    15.0   15   15   0.000000
59   33.000000    30.5   11   60  24.289916
60   36.333333    49.0    4   56  28.219379
63   47.000000    47.0   43   51   5.656854
64    3.000000     3.0    3    3        NaN
65   43.500000    43.5   35   52  12.020815
66   49.000000    49.0   48   50   1.414214
67   41.500000    46.5   14   59  19.773720
68   48.666667    48.0   43   55   6.027714
69   46.000000    46.0   46   46        NaN
70   55.500000    55.5   55   56   0.707107

In [28]:
print('summary statistics for gender grouped by annual income:')
df.groupby('Gender')['Annual Income (k$)'].agg(['mean','median','min','max','std'])

summary statistics for gender grouped by annual income:

             mean  median  min  max        std
Gender
Female  59.250000    60.0   16  126  26.011952
Male    62.227273    62.5   15  137  26.638373

In [29]:
print('summary statistics for age grouped by annual income:')
df.groupby('Age')['Annual Income (k$)'].agg(['mean','median','min','max','std'])

summary statistics for age grouped by annual income:

           mean  median  min  max        std
Age
18    51.250000    53.5   33   65  14.056434
19    57.000000    63.5   15   81  20.632845
20    41.600000    37.0   16   73  24.815318
21    38.800000    33.0   15   62  19.018412
22    31.333333    20.0   17   57  22.278540
23    41.500000    41.5   16   70  23.441416
24    39.250000    38.5   20   60  16.357975
25    57.666667    72.0   24   77  29.263174
26    58.000000    58.0   54   62   5.656854
27    63.166667    63.5   40   88  18.400181
28    85.250000    82.0   76  101  11.615363
29    63.600000    73.0   28   98  28.866936
30    76.142857    78.0   19  137  39.612408
31    48.375000    41.5   17   81  23.323425
32    87.181818    77.0   48  137  26.809768
33    80.333333    86.0   42  113  35.837597
34    79.000000    78.0   58  103  15.968719
35    46.666667    24.0   18  120  38.632888
36    81.000000    87.0   37  103  22.556595
37    65.000000    78.0   20   97  40.112342
38    74.500000    69.0   54  113  20.462160
39    72.666667    71.0   69   78   4.725816
40    61.666667    64.5   29   87  19.551641
41   101.000000   101.0   99  103   2.828427
42    60.000000    60.0   34   86  36.769553
43    65.666667    71.0   48   78  15.695010
44    75.500000    75.5   73   78   3.535534
45    69.333333    54.0   28  126  50.767444
46    59.000000    54.0   25   98  36.755952
47    70.166667    65.5   43  120  27.694163
48    58.200000    60.0   39   77  13.700365
49    51.000000    54.0   33   65  12.884099
50    58.600000    58.0   40   85  18.420098
51    55.500000    55.5   44   67  16.263456
52    55.500000    55.5   23   88  45.961941
53    39.500000    39.5   33   46   9.192388
54    59.750000    55.0   28  101  30.998656
55    57.000000    57.0   57   57        NaN
56    79.000000    79.0   79   79        NaN
57    64.500000    64.5   54   75  14.849242
58    54.000000    54.0   20   88  48.083261
59    65.250000    62.5   43   93  21.792583
60    43.333333    50.0   30   50  11.547005
63    56.500000    56.5   48   65  12.020815
64    19.000000    19.0   19   19        NaN
65    50.500000    50.5   38   63  17.677670
66    63.000000    63.0   63   63   0.000000
67    45.500000    50.5   19   62  18.699376
68    56.666667    59.0   48   63   7.767453
69    44.000000    44.0   44   44        NaN
70    47.500000    47.5   46   49   2.121320

In [30]:
import pandas as pd
dr=pd.read_csv("iris.csv")

In [31]:
dr.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [32]:
dr.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [34]:
data = dr[dr['Species'] == 'Iris-setosa']

print(data.mean(numeric_only=True))

Id               25.500
SepalLengthCm     5.006
SepalWidthCm      3.418
PetalLengthCm     1.464
PetalWidthCm      0.244
dtype: float64

In [37]:
data1 = dr[dr['Species'] == 'Iris-versicolor']

print(data1.mean(numeric_only=True))

Id               75.500
SepalLengthCm     5.936
SepalWidthCm      2.770
PetalLengthCm     4.260
PetalWidthCm      1.326
dtype: float64

In [38]:
data2 = dr[dr['Species'] == 'Iris-virginica']

print(data2.mean(numeric_only=True))

Id               125.500
SepalLengthCm      6.588
SepalWidthCm       2.974
PetalLengthCm      5.552
PetalWidthCm       2.026
dtype: float64

In [39]:
dr.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [40]:
data.quantile(0.25,numeric_only=True)

Id               63.250
SepalLengthCm     5.600
SepalWidthCm      2.525
PetalLengthCm     4.000
PetalWidthCm      1.200
Name: 0.25, dtype: float64

In [41]:
data.quantile(0.50,numeric_only=True)

Id               75.50
SepalLengthCm     5.90
SepalWidthCm      2.80
PetalLengthCm     4.35
PetalWidthCm      1.30
Name: 0.5, dtype: float64

In [42]:
data.quantile(0.75,numeric_only=True)

Id               87.75
SepalLengthCm     6.30
SepalWidthCm      3.00
PetalLengthCm     4.60
PetalWidthCm      1.50
Name: 0.75, dtype: float64

In [43]:
data.std(numeric_only=True)

Id               14.577380
SepalLengthCm     0.516171
SepalWidthCm      0.313798
PetalLengthCm     0.469911
PetalWidthCm      0.197753
dtype: float64

In [45]:
data1.std(numeric_only=True)

Id               14.577380
SepalLengthCm     0.516171
SepalWidthCm      0.313798
PetalLengthCm     0.469911
PetalWidthCm      0.197753
dtype: float64

In [46]:
data2.std(numeric_only=True)

Id               14.577380
SepalLengthCm     0.635880
SepalWidthCm      0.322497
PetalLengthCm     0.551895
PetalWidthCm      0.274650
dtype: float64